---
- hosts: all
  vars_files: 
    - vault.yml
  gather_facts: false
  roles:
    - luks-root
  post_tasks:
    - shell: reboot
      poll:  0
      async: 1
      ignore_errors: yes

    - local_action: wait_for port=22 host={{ ansible_host }} timeout=1600 delay=30
      register: wait
      until: wait|succeeded
      become: false

    - raw: 'echo -n {{ vars["passphrase_" + inventory_hostname|d(passphrase)|regex_replace("-","_")] }}>/lib/cryptsetup/passfifo'
      vars:
        ansible_ssh_user: 'root'

    - local_action: wait_for port=22 host={{ ansible_host }} timeout=1600 delay=10
      register: wait
      until: wait|succeeded
      become: false

