---

- shell: echo "UUID=\"`blkid /dev/md1 -s UUID -o value`\" / ext2 defaults 0 2" >> /mnt/etc/fstab
- shell: echo 'root UUID=`blkid /dev/md2 -s UUID -o value` none luks,discard'  >  /mnt/etc/crypttab

- copy:
    dest: "/mnt/etc/initramfs-tools/conf.d/cryptsetup"
    content: "CRYPTSETUP=y"

- copy:
    dest:    /mnt/etc/resolv.conf #not saved inside Dockerfile
    content: "nameserver 8.8.8.8"

- copy:
    dest:    "{{item}}/authorized_keys"
    src:     ~/.ssh/id_rsa.pub
    mode:    0644
  loop: 
    - /mnt/root/.ssh/
    - /mnt/etc/initramfs-tools/root/.ssh/
      
- lineinfile:
    dest: "{{item.file}}"
    line: '{{item.var}}="{{ ansible_facts.default_ipv4.address }}::{{ ansible_facts.default_ipv4.gateway }}:{{ansible_facts.default_ipv4.netmask }}:hostname:{{ansible_facts.default_ipv4.alias}}"'
    regexp: "{{item.var}}="
  loop:
    - {var: "GRUB_CMDLINE_LINUX=ip", file: /mnt/etc/default/grub                   }
    - {var: DEVICE,                  file: /mnt/etc/initramfs-tools/initramfs.conf }

- shell: >
    chroot /mnt /bin/bash -c "update-grub2 && update-initramfs -u -v"

- shell: chroot /mnt grub-install {{item}}
  loop: 
    - /dev/sda
    - /dev/sdb
