---
- shell: mdadm --stop --force {{item}}
  args:
    removes: /dev/md1
  loop: "{{ [ '/dev/md1' , '/dev/md2' ] }}"

- name: "wipefs partitions"
  shell: wipefs -af {{item}}
  loop: "{{ [ '/dev/sda' , '/dev/sdb' ] }}"

- name: "create partitions"
  shell: >
    /sbin/parted -s {{item}} 
    mklabel gpt
    disk_set pmbr_boot on
    unit GB
    mkpart primary 3MB 200MB
    set 1 raid on
    mkpart primary 200MB 100%
    set 2 raid on
    mkpart primary 1MB 3MB
    name 3 grub
    set 3 bios_grub on
   
  loop: "{{ [ '/dev/sda' , '/dev/sdb' ] }}"

- name: "create software raid"
  shell: mdadm --create /dev/md{{ item }} --level=1 --run --raid-devices=2 --metadata=1.0 /dev/sda{{ item }} /dev/sdb{{ item }}
  loop: [1,2]
