---
- shell: echo "UUID=\"`blkid {{luks_boot_md}} -s UUID -o value`\" /boot ext2 defaults 0 2" >> /mnt/etc/fstab
- shell: echo "root UUID=`blkid {{luks_root_md}} -s UUID -o value` none luks,discard"  >  /mnt/etc/crypttab

- copy:
    dest:    /mnt/etc/resolv.conf #not saved inside Dockerfile
    content: "nameserver 8.8.8.8"

- copy:
    dest:    "{{item}}/authorized_keys"
    src:     ~/.ssh/id_rsa.pub
    mode:    0644
  loop:
    - /mnt/root/.ssh/
    - /mnt/etc/dropbear-initramfs/

- lineinfile:
    dest:   "{{item.file}}"
    line:   '{{item.var}}{{ ansible_default_ipv4.address }}::{{ ansible_default_ipv4.gateway }}:{{ansible_default_ipv4.netmask }}:hostname:eth0"'
    regexp: "{{item.var | regex_replace('=.*$','') }}"
  loop:
    - {var: 'GRUB_CMDLINE_LINUX="net.ifnames=0 text debug=vc ip=', file: /mnt/etc/default/grub }
    - {var: 'DEVICE="IP=',               file: /mnt/etc/initramfs-tools/initramfs.conf }

- lineinfile:
    dest:   "/mnt/etc/initramfs-tools/initramfs.conf"
    line:   "DROPBEAR=y"

- lineinfile:
    dest:    /mnt/etc/default/dropbear
    line:   'NO_START=0'
    regexp: 'NO_START='
  tags: q
- lineinfile:
    dest:    /mnt/etc/default/grub
    line:   'GRUB_CMDLINE_LINUX_DEFAULT="text debug"'
    regexp: 'GRUB_CMDLINE_LINUX_DEFAULT'
  tags: q

- shell: >
    chroot /mnt /bin/bash -c "update-grub2 && update-initramfs -u -v "

- shell: chroot /mnt grub-install {{item}}
  loop: "{{luks_disks}}"
