---

- name: deploy-os | deploy OS using "docker export"
  shell: docker export root | tar xvf -
  args:
    chdir: /mnt
  tags: docker-export

- name: deploy-os | gather facts
  setup:

- name: deploy-os | update fstab,crypttab
  lineinfile:
    line: "{{item.line}}"
    dest: "{{item.dest}}"
  loop:
    - dest: /mnt/etc/fstab
      line: "UUID={{ansible_devices[luks_boot_md].links.uuids[0]}} /boot ext2 defaults 0 2"
    - dest:  /mnt/etc/crypttab
      line: "{{luks_mapp_name}} UUID={{ansible_devices[luks_root_md].links.uuids[0]}} none luks,discard"

- name: deploy-os | setup resolv.conf,interfaces.d
  copy:
    dest:    "{{item.dest}}"
    content: "{{item.content}}"
  loop:
    - dest:    "/mnt/etc/resolv.conf"
      content: "nameserver 8.8.8.8"
    - dest:    "/mnt/etc/network/interfaces.d/eth0"
      content: |
        auto eth0
        iface eth0 inet static
        address {{ ansible_facts.default_ipv4.address }}
        netmask {{ ansible_facts.default_ipv4.netmask }}
        gateway {{ ansible_facts.default_ipv4.gateway }}

- name: deploy-os | update initramfs.conf
  lineinfile:
    dest:   /mnt/etc/initramfs-tools/initramfs.conf
    regexp: "DEVICE="
    line:   'DEVICE="IP={{ ansible_default_ipv4.address }}::{{ ansible_default_ipv4.gateway }}:{{ansible_default_ipv4.netmask }}:hostname:eth0"'
