---

- name: luks-and-lvm | format luks device
  shell: echo {{ vars["passphrase_" + inventory_hostname|regex_replace("-","_")] | d(passphrase) }} | cryptsetup luksFormat /dev/{{luks_root_md}}
- name: luks-and-lvm | open luks device
  shell: echo {{ vars["passphrase_" + inventory_hostname|regex_replace("-","_")] | d(passphrase) }} | cryptsetup luksOpen   /dev/{{luks_root_md}} {{luks_mapp_name}}

- name: luks-and-lvm | create LVM volume group
  lvg:
    vg: "{{luks_lvm_name}}"
    pvs: "/dev/mapper/{{luks_mapp_name}}"

- name: luks-and-lvm | create "root" and "data" Logical Volumes
  lvol:
    size: "{{item.size}}"
    vg: "{{luks_lvm_name}}"
    lv: "{{item.name}}"
  loop:
    - name: root
      size: "{{luks_root_size}}"
    #- name: data
    #  size: "100%FREE"
