
- name: luks | generate passphrase
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters') }}"

- name: luks | encrypt vault
  local_action: command ansible-vault encrypt_string --vault-id 'luks@password.sh' --name "passphrase_{{inventory_hostname|regex_replace('-','_')}}" '{{passphrase}}'
  become: false
  register: encrypted_passphrase

- name: luks | store vault
  local_action:
    module: blockinfile
    block: "{{ encrypted_passphrase.stdout }}"
    path:  vault.yml
    insertbefore: BOF
    marker_begin: "{{inventory_hostname}}"
  become: false

- name: luks | format luks device
  shell: echo {{ passphrase }} | cryptsetup luksFormat /dev/{{luks_root_md}}
- name: luks | open luks device
  shell: echo {{ passphrase }} | cryptsetup luksOpen   /dev/{{luks_root_md}} root
