---
- include: prepare.yml
  tags:    prepare

- include: software-raid.yml
  tags:    software-raid

- include: luks-and-lvm.yml
  tags:    luks-and-lvm

- include: mount-chroot.yml
  tags:    mount-chroot

- include: deploy-os.yml
  tags:    deploy-os
