---
- include: purge-disks.yml
  tags:    purge-disks

- include: prepare.yml
  tags:    prepare

- include: software-raid.yml
  tags:    software-raid

- include: generate-luks-pass.yml
  tags:    generate-luks-pass

- include: luks-and-lvm.yml
  tags:    luks-and-lvm

- include: mount-chroot.yml
  tags:    mount-chroot

- include: deploy-os.yml
  tags:    deploy-os

- include: update-ssh-keys.yml
  tags:    update-ssh-keys
