---

#- name: prepare | install mdadm
  #package: name=mdadm

- name: prepare | install dockerd
  shell: >
    curl -sSL https://get.docker.com/ | sh && docker pull vych/ubuntu-luks-root
    && docker run  --name root vych/ubuntu-luks-root
  args:
    creates: /usr/bin/docker
