---

# CLEANUP

- name: prepare | cleanup stale chroot mounts
  shell: umount /mnt/* /mnt 2>/dev/null || true
  args:
    removes: /mnt/boot

- name: prepare | cleanup stale luks
  shell: cryptsetup close root
  args:
    removes: /dev/mapper/root

- name: prepare | get list of mdadm devices
  find:
    paths: /dev
    patterns: "md?"
    file_type: any
  register: md_devs

- name: prepare | mdadm purge
  shell: mdadm --stop --force {{item.path}}
  loop: "{{ md_devs.files }}"

- name: prepare | wipefs disks
  shell: wipefs -a {{item}}
  loop: "{{luks_disks}}"

# INSTALL DEPENDENCIES
#- name: prepare | install mdadm
  #package: name=mdadm

- name: prepare | install dockerd
  shell: >
    curl -sSL https://get.docker.com/ | sh
  args:
    creates: /usr/bin/docker
