---

- name: prepare | cleanup stale chroot mounts
  shell: umount -l /mnt/* /mnt 2>/dev/null || true
  args:
    removes: /mnt/boot

- name: prepare | cleanup stale luks
  #shell: dmsetup remove vg-root && dmsetup remove vg-data && cryptsetup close {{ luks_mapp_name }}
  shell: dmsetup remove vg-root && cryptsetup close {{ luks_mapp_name }}
  args:
    removes: /dev/mapper/{{ luks_mapp_name }}

- name: prepare | get list of mdadm devices
  find:
    paths: /dev
    patterns: "md?"
    file_type: any
  register: md_devs

- name: prepare | mdadm purge
  shell: mdadm --stop --force {{item.path}}
  loop: "{{ md_devs.files }}"

- name: prepare | wipefs disks
  shell: wipefs -a {{item}}
  loop: "{{luks_disks}}"
