---

- name: "partitions | create partitions"
  shell: /sbin/parted -s {{item}} {{luks_parted_script}}
  loop: "{{luks_disks}}"

- name: "partitions | create software raid (mirror)"
  shell: mdadm --create /dev/md{{ item }} --level=1 --run --raid-devices={{luks_disks|length}} --metadata=1.0 {{luks_disks[0]}}{{ item }} {{luks_disks[1]}}{{ item }}
  args:
    creates: "/dev/{{luks_root_md}}"
  loop: [1,2]
